version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - clean-code
      - test:
          requires:
            - clean-code
      - race:
          requires:
            - clean-code
      - compile:
          requires:
            - clean-code

jobs:
  clean-code:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/github.com/fearful-symmetry/garlic
    steps:
      - checkout
      - run:
          name: Run go vet
          command: go tool vet *.go
      - run:
          name: Run golint
          command: |
            go get -u github.com/golang/lint/golint
            golint ./
      - run:
          name: gofmt
          command: test -z $(gofmt -s -l \*.go fswatch nagios)
  test:
    environment:
      - GO111MODULE: on
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/github.com/fearful-symmetry/garlic
    steps:
      - checkout
      - run:
          name: Test all
          command: go test -a
      - run:
          name: Test coverage
          command: go test -cover
  race:
    environment:
      - GO111MODULE: on
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/github.com/fearful-symmetry/garlic
    steps:
      - checkout
      - run:
          name: Race detector
          command: go test -race
  compile:
    environment:
      - GO111MODULE: on
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/github.com/fearful-symmetry/garlic
    steps:
      - checkout
      - run:
          name: build garlic
          command: |
            go build -a